import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import products from "../products.json";
import useCart from "../hooks/use-cart";

export default function Home() {
  const { cart, addToCart, checkout } = useCart();

  console.log("Cart: ", JSON.stringify(cart));

  return (
    <div className={styles.container}>
      <Head>
        <title>Hemdem Art</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Hemdem Art</h1>
        <p className={styles.description}>Beautiful Illumination Artwork</p>
        <p className={styles.description}>
          <strong>Items: {Object.keys(cart.products).length}</strong>
          <br />
          <strong>Total cost: £{cart.total}</strong>
          <br />
          <button className={styles.button} onClick={() => checkout()}>
            Checkout
          </button>
        </p>
        <section className={styles.grid}>
          {products.map(({ id, title, description, image, price }) => (
            <div className={styles.card} key={id}>
              <Image src={image} alt={`${title} illumination artwork`} height={600} width={400} />
              <h2>{title}</h2>
              <p className={styles.price}>
                <strong>£{price}</strong>
              </p>
              <p>{description}</p>
              <button
                className={`${styles.button} ${cart.products[id] ? styles.disabled : ""}`}
                onClick={() => {
                  addToCart({ id });
                }}
              >
                Buy
              </button>
            </div>
          ))}
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Design by Koders.co
        </a>
      </footer>
    </div>
  );
}
