import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import products from "../products.json";
import { initiateCheckout } from "../lib/payments";

export default function Home() {
  console.log("NEXT_PUBLIC_STRIPE_API_KEY: ", process.env.NEXT_PUBLIC_STRIPE_API_KEY);
  return (
    <div className={styles.container}>
      <Head>
        <title>Serife Orak Art</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Serife Orak Art</h1>
        <p className={styles.description}>Beautiful Illumination Artwork</p>
        <ul className={styles.grid}>
          {products.map(({ id, title, description, image, price }) => (
            <li className={styles.card} key={id}>
              <Image src={image} alt={`${title} illumination artwork`} height={600} width={400} />
              <h2>{title}</h2>
              <p className={styles.price}>
                <strong>£{price}</strong>
              </p>
              <p>{description}</p>
              <p>
                <button
                  className={styles.button}
                  onClick={() => {
                    initiateCheckout({ lineItems: [{ price: id, quantity: 1 }] });
                  }}
                >
                  Buy
                </button>
              </p>
            </li>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Design by Koders.co
        </a>
      </footer>
    </div>
  );
}
